services:
  datasafe:
    build:
      args:
        JAR_FILE: "datasafe-rest-impl.jar"
#    image: adorsys/datasafe
    environment:
      EXPOSE_API_CREDS: true
      DEFAULT_USER: username
      DEFAULT_PASSWORD: password
      USE_FILESYSTEM: file:///usr/app/ROOT_BUCKET
    ports:
      - 8080:8080
    volumes:
      - "./ROOT_BUCKET:/usr/app/ROOT_BUCKET"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
