name: Develop branch build
on:
  workflow_call:

jobs:
  codecov-job:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage unittests reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true